### ISSUE TITLE
[BUG] Fix the Top Charts Component for medium screen sizes

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#84]
The top Charts component looks fine on the large screen size (15.6 & more ) 
![image](https://user-images.githubusercontent.com/64729135/194606247-45520d8b-3f93-46ce-9e98-b923e5bec0b8.png)

But it needs to be fixed for small screen laptops and medium screens 
![image](https://user-images.githubusercontent.com/64729135/194606778-dd2a7054-30ef-4365-b10c-9506871dc838.png)

**Comment by bkjain655** [comment]
Hi @Aman-Mandal ,

Can you please elaborate the issue here?
I forked your repo and tried on my 13.3 laptop (Chrome browser) & it seems to be fine.
Please find attached screenshot.
<img width="1440" alt="Screenshot 2022-10-07 at 23 05 14" src="https://user-images.githubusercontent.com/32372388/194617181-c57ed4aa-1fd3-4d78-bf52-fa459dafd0c9.png">

**Comment by Aman-Mandal** [comment]
> Hi @Aman-Mandal ,
> 
> Can you please elaborate the issue here?
> I forked your repo and tried on my 13.3 laptop (Chrome browser) & it seems to be fine.
> Please find attached screenshot.
> <img width="1440" alt="Screenshot 2022-10-07 at 23 05 14" src="https://user-images.githubusercontent.com/32372388/194617181-c57ed4aa-1fd3-4d78-bf52-fa459dafd0c9.png">
> 

See the songs in the top charts component.. they are not aligned properly!! 

The image and the song name are not looking fine..you can see it in your screenshot too

**Comment by rafaeldias97** [comment]
@Aman-Mandal 
I solved the problem, could you assign me ?
